components/home/PosterDetail.module.css, components/home/PosterImageBox.module.css, components/home/UserPoster.module.css
1. 이미지 박스의 사이즈를 25vh -> 20vh로 수정 [PosterImageBox.module.css]
2. 게시글의 폰트를 반응형으로 수정 [PosterDetail.module.css]
3. 스타일의 중복된 코드 제거 [UserPoster.module.css]
=> Home userPoster 디자인 변경 

components/footerbar/FooterBar.module.css
푸터가 하단에 고정되도록 속성추가 + 푸터의 사이즈가 화면의
좌우 사이즈에 맞도록 고정
=> design: footer css 속성추가

pages/api/logined.js, pages/api/utils/verifyToken.js
기능은 두가지를 구현함 
1. 토큰을 검증할 함수
2. 로그인이 유지되어 있을때 항상 받아야 할 정보를 건내줘야할 함수 [ 토큰을 검증해야하는 함수를 호출함 ]
1번의 기능은 여러곳에 쓰일 예정임
=> Page/be 토큰검증 및 유저정보 호출 기능구현

pages/_app.js
로컬스토리지에 담긴 토큰을 api 호출로 검증 후 정보를 받아온 후
페이지에 유저정보를 전달함
=> feat: 유저 로그인 검증 및 정보 호출기능 구현

components/topbar/AlertBell.js, components/topbar/AlertBell.module.css, components/topbar/LoginButton.module.css, components/topbar/LoginCheck.js
1. AlertBell.js -> 알림 버튼을 원래 이미지로 던져줬으나 react-icon으로 변경 
2. AlertBell.module.css -> 알림 버튼의 스타일 코드 변경 - 색상 + 폰트사이즈추가
3. LoginCheck.js -> 로그인 상태에 따라 알림벨과 로그인창중 선택적으로 뜨게하는 로직추가 
3-1. 원래는 db와 연결되어 있지 않아서 항시 로그인상태로 던져줬으나 지금은 db와 연결로 로그인을 체크 후 선택적으로 던져줌
4. LoginCheck.module.css -> 로그인 버튼에 마진을 5px 추가
=> Home topbar 리팩토링 

components/footerbar/FooterBar.js, components/footerbar/FooterBar.module.css, components/footerbar/NavItem.js, components/footerbar/Navitem.module.css
footerbar의 컴포넌트 분리, 코드 리팩토링 및 css 디자인 수정
=> Home footerbar

components/footerbar/FooterBar.js, components/footerbar/Navitem.module.css
footerbar에 전달되는 유저 프로필에 따라 내정보의 이미지가 변환되도록 수정 
내정보의 이미지가 렌더링 될 시 스타일 추가
=> footerbar바 리팩토링 및 스타일 추가 

pages/MyPage.js, pages/alert.js, pages/chat.js, pages/detail.js, pages/login.js, pages/reviewwrite.js, pages/write.js
페이지의 props로 user를 받아오는것 추가
푸터바가 존재하거나 탑바의 login체크가 존재해야 할 경우 
props의 user정보를 건내주게 수정
=> 일부 page 리팩토링

pages/MyPage.js, pages/_app.js
mypage -> 불필요한 import 제거 및 조건부 렌더링 추가
_app.js -> 사용자 검증 최적화 및 로딩 상태 관리 추가
=> App.js , mypage 업데이트 

components/login/Kakao.js
값은 임의로 설정 [20살로]
만약 사업자 신청이 된다면 카카오에서 제공받을 수 있음
=> refactor: 유저 가입정보에 gender추가

components/MyPage/UserProfileDetail.js, components/MyPage/UserTapBar.js, components/login/Kakao.js, pages/MyPage.js, pages/_app.js, pages/api/auth/kakao.js, pages/api/lib/models/user.model.js, pages/api/lib/models/write.model.js, pages/api/logined.js
추후 작업을 위해 props를 유저로 받고 콘솔로 찍어보도록 변경
=> feat: props로 user를 받도록 수정

components/home/PosterImageBox.js, components/postDetail/HeartIconToggle.js, components/postDetail/HeartIconToggle.module.css, components/postDetail/UserPostInfo.js, components/postDetail/UserPostInfo.module.css
UserPostInfo 에 HeartIconToggle 컴포넌트 추가
하트 아이콘 누르면 애니메이션,색상 적용
=> feat:게시물 좋아요 기능 추가

components/MyPage/UserPostContents.js, components/MyPage/UserPostContents.module.css, components/MyPage/UserProfileDetail.js, components/MyPage/UserProfileDetail.module.css
마이페이지 
- 게시물 탭 컨텐츠 hover시 동행 날짜가 보이도록 수정
- 프로필 수정 박스 안 아이콘 교체
=> design: 게시물 탭 content css 수정 및 프로필 수정 박스 아이콘 수정

pages/_app.js, pages/alert.js, pages/mypage.js, styles/global.css
1. 구글 Inter 폰트 전역으로 설정
2. 마이페이지 탑바 추가
3. 알림 페이지 탑바를 컴포넌트에서 불러오고 있던걸 페이지에서 불러오게 변경
=> 전역 폰트 추가 및 페이지 컴포넌트 추가

components/MyPage/UserProfileDetail.js, components/MyPage/UserProfileDetail.module.css, components/MyPage/UserTogetherContents.js, components/MyPage/UserTogetherContents.module.css
1. UserProfileDetail.js
1-1. age, gender의 스타일이 같으므로 하나로 통합
1-2. import icon all은 모든 아이콘을 가져옴 -> 사용할거만 가져와야함 [ 변경 ]
2. UserProfileDetail.module.css
유저 프로필의 스타일을 좀더 친화적으로 변경
3. UserTogetherContents.js
아이콘을 이미지에서 리액트 아이콘으로 교체 , 고유키값 설정, 필요하지 않은 돔제거
4. UserTogetherContents.module.css
컨텐츠가 라인에 2개씩 오도록 설정 및 대략적인 스타일 수정
=> Mypage user profile디자인 개선 및 최적화

components/notification/Notifications.js, components/notification/Notifications.module.css
1.더미데이터 icon값에 따라 달라지는 아이콘 추가(case문)
2.css 간격 수정 
3.쓰이지 않은 코드 리팩토링
=> feat: icon 설정값에 따른 아이콘 추가

components/notification/Notifications.module.css
=> design:알림창 간격 조정

pages/reviewwrite.js, pages/write.js
pages
ㄴreviewwrite.js
- 여행 리뷰 작성 페이지에 탑바와 푸터바 추가
=> feat: 여행 리뷰 작성 페이지 탑바, 푸터바 추가

components/chat/ChatList.module.css, components/chatroom/ChatRoom.module.css
1.채팅창 프로필 이미지 크기 50px->40px
2.채팅방 목록의 unreadCount, chatTime간격 조정
=> design:채팅방 디자인 수정

components/writeReview/writeReview.js, components/writeReview/writeReview.module.css
writeReview
- classname 추가
- 글씨 크기 및 굵기, 간격 조정 등 CSS 수정
=> design: 여행 리뷰 작성 페이지 CSS 수정

components/MyPage/UserPostContents.js, components/MyPage/UserPostContents.module.css
UserPostContents
- 동행 탭과 CSS 통일 
- 불필요한 코드 삭제 및 CSS 삭제
=> design: 게시글 탭 CSS 수정

pages/chat.js, pages/mypage.js, pages/mypage/update.js
**mypage**
middleContent수정 -> {user.name}님의 마이페이지
**mypage/update**
탑,푸터바 추가
**chat**
탑,푸터바 추가
=> feat:페이지별 탑,푸터바 추가

components/footerbar/FooterBar.module.css
FooterBar
- 푸터바의 색상을 흰색으로 변경
- 푸터바 위쪽에 경계를 알 수 있도록 그림자 추가
=> design: 푸터바 색상 변경 및 CSS 수정

pages/mypage.js
=> feat: 마이페이지 푸터바 추가

pages/mypage/update.js
=> feat: ProfileUpdate 컴포넌트에 유저정보 전달

components/mypageUpdate/IdUpdate.js, components/mypageUpdate/IdUpdate.module.css, components/mypageUpdate/ImgUpdateBtn.js, components/mypageUpdate/ImgUpdateBtn.module.css, components/mypageUpdate/IntroUpdate.js, components/mypageUpdate/IntroUpdate.module.css, components/mypageUpdate/ProfileUpdate.js, components/mypageUpdate/ProfileUpdate.module.css, components/mypageUpdate/snsLogin.module.css
1. 유저 업데이트에 들어갈 전체적인 디자인 수정
2. 업데이트 페이지별 유저정보에 들어갈 프롭스 전달 및 첫렌더링시 보여질 이미지,텍스트들을 적용
3. 불필요한 요소 삭제 및 리팩토링
=> Mypage Update 디자인 변경 및 유저 프롭스 전달

components/MyPage/UserProfileDetail.js, components/MyPage/UserProfileDetail.module.css
=> design: 마이페이지 CSS 수정

components/user_write/DateSelect.module.css, components/user_write/GenderAgeSelect.js, components/user_write/GenderAgeSelect.module.css, components/user_write/TravelMap.js, components/user_write/TravelMap.module.css, components/user_write/write.module.css
1.사용자 정보 등록란 디자인 수정
2.날짜 선택란 디자인 수정
3.타이틀에 아이콘 추가
4.장소검색 디자인 수정
=> design:게시글 작성 페이지 디자인 수정

pages/write.js
- 게시글 작성 placeholder에 동행글 팁(mbti,여행목적) 작성
- 아이콘 추가
=> design:write페이지 디자인 추가

components/topbar/LoginButton.module.css, components/topbar/SearchBar.module.css, components/topbar/TopBar.module.css
top bar
- 검색바 밑 여백 추가
- (검색바가 없는)탑바 경계선 수정
- 검색 아이콘 위치 조정
- 검색 아이콘 색 조정
- 로그인 텍스트 폰트 굵기 수정
=> design: 탑바 CSS 수정

components/home/PosterDetail.js, components/home/PosterDetail.module.css, components/home/PosterImageBox.js, components/home/PosterImageBox.module.css, components/home/UserPoster.module.css, components/home/index.module.css
home
- 상단 위치 아이콘 통일 (마이페이지 위치 아이콘과 종류가 달라 이 부분 통일)
- 상단 위치 부분 패딩 수치 조정
- 사진 하단 디테일 부분 패딩 수치 조정
- 사진 하단 디테일 부분 가시성을 위해 아이콘 추가
- 하트버튼 배경 삭제
- shadow 수치 조정
- 탑바와 컨텐츠간의 간격 조정 및 컨텐츠들 사이의 간격 조정
등 수정했습니다!
=> design: 홈화면 CSS 수정

components/chat/ChatList.js, components/chat/ChatList.module.css
채팅방 이미지,텍스트 등이 사이좋게 달라붙어 있어 마진을 줬습니다.
=> design:채팅방 목록 마진 조정

package-lock.json, package.json, pages/api/lib/models/write.model.js, pages/api/uploadImages.js, pages/api/writeInput.js
1. writeDB 스키마 수정
2. 이미지 & 글쓰기 엔드포인트 API 분리 완료
=> feat: writeDB스키마 수정, 이미지 & 글쓰기 엔드포인트 API 분리 완료

components/user_write/DateSelect.module.css, components/user_write/GenderAgeSelect.js, components/user_write/GenderAgeSelect.module.css, components/user_write/HeadcountSelect.js, components/user_write/HeadcountSelect.module.css, components/user_write/write.module.css
1. write.module.css->게시물 글 작성placeholder줄간격 조정 
2. DateSelect->여행 날짜 수평정렬, 버튼 색상 옅게 수정
3. GenderAgeSelect->성별,나이 수평정렬,폰트 굵기 수정,버튼 색상 옅게 수정
4. HeadCountSelect->동행인원 수평정렬, 폰트굵기 수정, 버튼 색상 옅게 수정
=> design:게시물 글쓰기 페이지 디자인 수평정렬

pages/write.js
placeholder부분,아이콘 추가 등 디자인 부분 복구 완료했습니다
=> design:게시글 작성 placeholder 문구 변경, 아이콘 추가

pages/api/lib/models/write.model.js, pages/api/saveLocation.js, pages/api/writeInput.js
1. saveLocation.js :구글지도검색위치 저장 서버api 추가
2. writeInput.js: 글쓰기 서버api 수정 -> 위치 추가로 인한 업데이트
3. write.mode.js: write스키마에 위치스키마 추가
=> feat: 구글지도검색위치 저장 서버api 추가, 글쓰기 서버api 수정, write스키마에 위치스키마 추가

components/mypageUpdate/IdUpdate.js, components/mypageUpdate/IdUpdate.module.css, components/mypageUpdate/IntroUpdate.js, components/mypageUpdate/IntroUpdate.module.css, components/mypageUpdate/ProfileUpdate.js, components/mypageUpdate/Submit.js, components/mypageUpdate/Submit.module.css
1. 유저의 이름과 설명이 변경될때 상향식으로 전달하고 submit에 props로 전달하도록 설정
2. submit버튼 추가
=> Mypage Update 버튼 추가 및 상태관리 변경 

components/user_write/TravelMap.js, components/user_write/TravelMap.module.css
1. TravelMap.js : 구글지도 api 프론트엔드 연결 & 렌더링 / 위치저장 버튼 css 수정
=> feat: 구글지도 api 프론트엔드 연결 & 렌더링 / 위치저장 버튼 css 수정

pages/api/userUpdate.js
아직 이미지는 구현 하지못했음 만들어져있는 api를 쓰면되긴하나 ..
로직의 문제가 생길만한 부분이 있어서 추후 예정
=> feat: 유저 업데이트 api 기능 구현

components/mypageUpdate/Submit.js
유저 intro와 닉네임 변경기능 구현
이미지는 추후예정
=> feat: 유저 업데이트 기능 구현

components/mypageUpdate/ImgUpdateBtn.js, components/mypageUpdate/ProfileUpdate.js, components/mypageUpdate/Submit.js
1. 이미지의 상태관리전달을 위한 훅 추가 ProfileUpdate.js
2. 상향식으로 이미지의 변경사항을 전달 ImgUpdateBtn.js
3. submit 누를시 전달받은 유저 정보를 업데이트 하는 로직 추가 Submit.js
Submit.js 업데이트 경우 post요청을 2번날림 
유저의 이름, 인트로 변경을 위한 post, 이미지 변경을 위한 post
나중에 변경필요
=> 마이페이지 업데이트 로직 구현

components/writeReview/StarRating.js, components/writeReview/StarRating.module.css
starrating
- 기본 별점의 색상을 회색으로 변경
=> design: 별점 CSS 수정

components/home/PosterDetail.module.css
PosterDetail
- 아이콘과 텍스트 사이의 간격 조정
- 아이콘과 텍스트 수평정렬
- 화면크기가 작아졌을시 텍스트 크기가 작아지도록 CSS 수
=> design: 홈화면 detail CSS 수정

pages/write.js
1. write 클라이언트 페이지 & write 서버 엔드포인트 api 연결(이미지 업로드, 구글 지도검색 위치 저장, 글작성 전체 데이터)
2. useEffect 추가
3. write 페이지 위치 저장 로직 수정(위치저장 버튼 삭제 등)
=> write.js 페이지 코드 수정

components/chatroom/menu/ChatInfo.module.css, components/chatroom/menu/ChatUser.js, components/chatroom/menu/ChatUser.module.css, components/chatroom/menu/CheckBox.module.css, components/chatroom/menu/ReviewBtn.js, components/chatroom/menu/ReviewBtn.module.css
1.동행 후기 작성 버튼 크기 변경
2.채팅방 메뉴 간격 조정
3.체크 박스 간격 조정
=> design:채팅방 메뉴 디자인 수정

components/login/LoginContents.module.css
login
- 로그인하고 여행을 계속해요 텍스트 옆 줄 추가
- 비행기 아이콘 키프레임 조정
=> design: 로그인 페이지 CSS 수정

components/MyPage/UserProfileDetail.js, components/MyPage/UserProfileDetail.module.css
=> design: 프로필 CSS 수정

components/home/PosterDetail.js, components/home/PosterImageBox.js, components/home/UserPoster.js, components/home/UserPoster.module.css
1. 무한스크롤 기능구현 [ 스크롤이 가장하단 + 첫렌더시 10개의 페이지를 요청하는기능 구현 ]
2. props를 컴포넌트에 맞춰 전달 후 받은 프롭스를 컴포넌트의 양식에 맞춰 가공 후 표현
3. link 디자인 초기화
=> Home의 유저 포스터와 API연결 및 Props전달, 무한스크롤 기능구현 

pages/write.js
프론트에서 디코드된 값을 받아서 API에게 저장을 요청함
보안상의 문제가 있는 부분인 113~140번, 156번, 166번 코드 삭제와
181번라인의 토큰을 보내주기때문에 백엔드의 로직에서 토큰검증후 디코드된 값의 아이디를 넣어주도록 수정
=> #104 보안이슈 수정

components/login/LoginContents.js
=> Refactor: 이미지 소스 파일명 대소문자 변경

pages/api/image-upload.js
=> Refactor: 이미지 저장경로 변경

next.config.js, package.json, server.js
1. nextConfig에서 reactStrictMode 값을 true에서 false로 변경함 [ 두번 출력방지 ]
2. package.json에서 start 스크립트를 next start에서 node server.js로 변경함
3. server.js 파일을 통한 사용자 정의 서버 설정 추가함
=> feat: React Strict Mode 변경, 사용자 정의 서버 설정 추가 및 시작 스크립트 업데이트

components/chat/ChatList.module.css, components/chatroom/ChatRoom.js, components/chatroom/ChatRoom.module.css, components/chatroom/MyChat.module.css, components/chatroom/menu/ReviewBtn.js, components/chatroom/menu/ReviewBtn.module.css
1.채팅방 말풍선 간격 조정
2.채팅방 목록의 동행후기 작성버튼과 여행리뷰작성 페이지 연결
=> design:채팅방 마진 조정, 동행리뷰 링크 연결

components/login/LoginContents.js
=> docs: 로그인 페이지 이미지 경로 수정

components/writeReview/StarRating.js, components/writeReview/StarRating.module.css, components/writeReview/writeReview.js, components/writeReview/writeReview.module.css
1. 후기 권장하는 문구와 아이콘을 추가/귀여운 문구로 홀린 듯 후기를 작성하게 하는 효과를 줍니다
2. 전체적인 너비와 폰트 사이즈 수정
=> design:동행 후기 작성 페이지 디자인 변경

components/MyPage/UserPostContents.js, components/MyPage/UserTapBar.js, components/MyPage/UserTogetherContents.js
1. UserTapBar에서 불러오는 컴포넌트에 Props전달
2. UserPostContents 에서 토글 활성화시 새롭게 API요청하여 렌더링 하는 로직 구현
=> feat: 유저페이지 게시글 요청 API 호출 및 렌더링, 상위 컴포넌트에서 프롭스 전달

components/user_write/DateSelect.js, components/user_write/DateSelect.module.css, components/user_write/GenderAgeSelect.js, components/user_write/GenderAgeSelect.module.css, components/user_write/HeadcountSelect.js, components/user_write/HeadcountSelect.module.css, components/user_write/write.module.css
=> design: 글쓰기 페이지 CSS 수정

pages/api/user/[id].js
=> feat: 페이지의 유저 프로필 GET요청 기능 구현

components/MyPage/UserProfileDetail.js
프로필이 나의 프로필 조회뿐만 아닌 타인의 프로필 조회를 할 경우를
대비해서 새로운 props추가됨
해당 props는 프로필수정 버튼을 렌더할지 말지 결정함
=> refactor: 컴포넌트 재사용을 위한 props 추가

components/mypageUpdate/IdUpdate.module.css, components/mypageUpdate/IntroUpdate.module.css, components/mypageUpdate/snsLogin.module.css
mypageupdate
- box-shadow 수정
- text 크기 및 굵기 수정
=> design: 마이페이지 수정페이지 CSS 수정

components/chat/ChatList.module.css, components/chatroom/ChatBar.module.css, components/chatroom/ChatRoom.js, components/chatroom/ChatRoom.module.css, components/chatroom/InputChat.js, components/chatroom/MapBtn.js, components/chatroom/MapBtn.module.css, components/chatroom/RequestButton.module.css, components/chatroom/SendBtn.js, components/chatroom/SendBtn.module.css
1. ChatList->채팅방 목록 프로필 이미지 그림자 추가, 이미지 크기, 폰트 조정
2. CatBar->채팅방 입력창과 전송버튼 색 통일, 간격 조정
지도 아이콘 변경
=> design:채팅방,채팅 전송창 디자인 수정

components/login/Kakao.module.css
카카오 로그인 버튼에 그림자 추가했습니다. 어색해 보일 때는 그림자 분신이죠
=> design:카카오 로그인 그림자 추가

pages/detail/[id].js
=> refactor: props에 유저 고유 아이디 추가

components/MyPage/UserPostContents.module.css
=> design: 마이페이지 게시물 높이 조정

components/MyPage/UserPostContents.js, components/home/PosterImageBox.module.css
=> 마이페이지 컨텐츠 클릭시 해당 컨텐츠 페이지로 이동, 홈 컨텐츠 사이즈조정

components/login/LoginContents.module.css
=> design: login CSS 수정

components/login/LoginContents.js, components/login/LoginContents.module.css
=> design: 로고 이미지 변경 및  CSS 수정

components/postDetail/TravelChatBtn.js
=> docs: 실험실 기능 Text 추가

pages/index.js, pages/index.module.css, pages/write.js
=> design:마진탑, max-width 추가

components/topbar/Gearbar.js, components/topbar/Logo.js
마이페이지 상단 톱니 아이콘에 실험실 기능 텍스트를 추가했습니다!
=> docs: 텍스트 추가

components/MyPage/UserTapBar.js
=> docs: 실험실 Text 추가

components/user_write/write.module.css
=> design:이미지 추가 아이콘 디자인 변경
